theme:        jekyll-theme-cayman

# Setup
title:        Programaci칩n e implementaciones con R
baseurl:      ""
paginate:     1
exclude:      [vendor]
simple_search: https://www.google.com/search
locale:       "es"

# About/contact
author:
  name:       Cristian Santa
  repository: cdsantae/cdsantae.github.io

collections:
  EAFIT:
    output: true
    title: Introducci칩n al manejo de datos con R y RStudio
    main: 1
    description: Curso orientado al aprendizaje b치sico de programaci칩n en R

# Gems
gems:
  - jekyll-theme-cayman
#Others
markdown: kramdown
