theme:        jekyll-theme-cayman

# Setup
title:        Programación e implementaciones con R
baseurl:      ""
paginate:     1
exclude:      [vendor]
simple_search: https://www.google.com/search
locale:       "es"
exclude: README.md

# About/contact
author:
  name:       Cristian Santa
  repository: cdsantae/cdsantae.github.io

collections:
  EAFIT:
    output: true
    title: EAFIT - Introducción al manejo de datos con R y RStudio
    main: 1
    description: Cursos orientados al aprendizaje de programación en R

# Gems
gems:
  - jekyll-theme-cayman
#Others
markdown: kramdown
