theme:        jekyll-theme-cayman

# Setup
title:        R y Rstudio
tagline:      Blah blah
baseurl:      ""
paginate:     1
locale:       "es"

# About/contact
author:
  name:       Cristian Santa
  url:        https://cdsantae.github.io/CursoR/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
